"""
Youtube ChannelIDから[ID,Tag]を取得
"""
def getLiveTag(ID:str)->str:
    HoloName = ''
    live_tag = ''
    symbol  = ''
    if ID == 'UChAnqc_AY5_I3Px5dig3X1Q': HoloName, live_tag, symbol = '戌神ころね', '#生神もんざえもん','🥐'
    elif ID == 'UC-hM6YJuNYVAmUWxeIr9FeA' : HoloName, live_tag, symbol  = 'さくらみこ', '#みこなま', '🌸'
    elif ID == 'UCdn5BQ06XqgXoAxIhbqw5Rg' : HoloName, live_tag, symbol  = '白上フブキ', '#フブキCh', '🌽'
    elif ID == 'UC1opHUrw8rvnsadT-iGp7Cg' : HoloName, live_tag, symbol  = '湊あくあ', '#湊あくあ生放送', '⚓️'
    elif ID == 'UC1DCedRgGHBdm81E1llLhOQ' : HoloName, live_tag, symbol  = '兎田ぺこら', '#ぺこらいぶ', '👯'
    elif ID == 'UCFTLzh12_nrtzqBPsTCqenA' : HoloName, live_tag, symbol = 'アキ・ローゼンタール', '#アキびゅーわーるど', '🍎'
    elif ID == 'UCp6993wxpyDPHUpavwDFqgg' : HoloName, live_tag, symbol  = 'ときのそら', '#ときのそら生放送', '🐻'
    elif ID == 'UCvzGlP9oQwU--Y0r9id_jnA' : HoloName, live_tag, symbol  = '大空スバル', '#生スバル', '🚑'
    elif ID == 'UCDqI2jOz0weumE8s7paEk6g' : HoloName, live_tag, symbol = 'ロボ子さん', '#ロボ子生放送', '🤖'
    elif ID == 'UCXTpFs_3PqI41qX2d9tL2Rw' : HoloName, live_tag, symbol  = '紫咲シオン', '#紫咲シオン', '🌙'
    elif ID == 'UCvInZx9h3jC2JzsIzoOebWg' : HoloName, live_tag, symbol  = '不知火フレア', '#フレアストリーム', '🔥'
    elif ID == 'UCD8HOxPs4Xvsm8H0ZxXGiBw' : HoloName, live_tag, symbol  = '夜空メル', '#メル生放送', '🌟'
    elif ID == 'UC1suqwovbL1kzsoaZgFZLKg' : HoloName, live_tag, symbol  = '癒月ちょこ', '#癒月診療所', '💋'
    elif ID == 'UCp3tgHXw_HI0QMk1K8qh3gQ' : HoloName, live_tag, symbol  = '癒月ちょこ', '#癒月診療所', '💋' #サブ
    elif ID == 'UC1CfXB_kRs3C-zaeTG3oGyg' : HoloName, live_tag, symbol = '赤井はあと', '#はあちゃまなう', '❤️'
    elif ID == 'UCvaTdHTWBGv3MKj3KVqJVCw' : HoloName, live_tag, symbol  = '猫又おかゆ', '#生おかゆ', '🍙'
    elif ID == 'UCa9Y57gfeY0Zro_noHRVrnw' : HoloName, live_tag, symbol  = '姫森ルーナ', '#なのらいぶ', '🍬'
    elif ID == 'UC5CwaMl1eIgY8h02uZw7u8A' : HoloName, live_tag, symbol  = '星街すいせい', '#ほしまちすたじお', '☄️'
    elif ID == 'UCQ0UDLQCjY0rmuxCDE38FGg' : HoloName, live_tag, symbol  = '夏色まつり', '#夏まつch', '🏮'
    elif ID == 'UCCzUftO8KOVkV4wQG1vkUvg' : HoloName, live_tag, symbol  = '宝鐘マリン', '#マリン航海記', '🏴‍☠️'
    elif ID == 'UC7fk0CB07ly8oSl0aqKkqFg' : HoloName, live_tag, symbol  = '百鬼あやめ', '#百鬼あやめch', '😈'
    elif ID == 'UCdyqAaZDKHXg4Ahi7VENThQ' : HoloName, live_tag, symbol  = '白銀ノエル', '#ノエルーム', '⚔️'
    elif ID == 'UCl_gCybOJRIgOXw6Qb4qJzQ' : HoloName, live_tag, symbol  = '潤羽るしあ', '#るしあらいぶ', '🦋'
    elif ID == 'UCS9uQI-jC3DE0L4IpXyvr6w' : HoloName, live_tag, symbol  = '桐生ココ', '#桐生ココ', '🐉'
    elif ID == 'UCZlDXzGoo7d44bwdNObFacg' : HoloName, live_tag, symbol  = '天音かなた', '#天界学園放送部', '💫'
    elif ID == 'UCp-5t9SrOQwXMU7iIjQfARg' : HoloName, live_tag, symbol  = '大神ミオ', '#ミオかわいい', '🌲'
    elif ID == 'UC1uv2Oq6kNxgATlCiez59hw' : HoloName, live_tag, symbol  = '常闇トワ', '#トワイライブ', '👾'
    elif ID == 'UCqm3BQLlJfvkTsX_hvm0UmA' : HoloName, live_tag, symbol  = '角巻わため', '#ドドドライブ', '🐏'
    elif ID == 'UCFKOVgVbGmX65RxO3EtH3iw' : HoloName, live_tag, symbol  = '雪花ラミィ', '#らみらいぶ', '☃️'
    elif ID == 'UCAWSyEs_Io8MtpY3m-zqILA' : HoloName, live_tag, symbol  = '桃鈴ねね', '#ねねいろらいぶ', '🥟'
    elif ID == 'UCUKD-uaobj9jiqB-VXt71mA' : HoloName, live_tag, symbol  = '獅白ぼたん', '#ぐうたらいぶ', '👅'
    elif ID == 'UCK9V2B22uJYu3N7eR_BT9QA' : HoloName, live_tag, symbol  = '尾丸ポルカ', '#ポルカ公演中', '🎪'
    # elif ID == 'UCgZuwn-O7Szh9cAgHqJ6vjw' : HoloName = '魔乃アロエ'
    # イノナカミュージック
    elif ID == 'UC0TXe_LYZ4scaW2XMyi5_kw' : HoloName, live_tag, symbol  = 'AZKi', '#AZKi', '⚒️'
    #ホロライブ　EN
    elif ID == 'UCL_qhgtOy0dy1Agp8vkySQg' : HoloName, live_tag, symbol  = '森美声', '#calliolive', '💀'
    elif ID == 'UCHsx4Hqa-1ORjQTh9TYDhww' : HoloName, live_tag, symbol  = '小鳥遊キアラ', '#キアライブ', '🐔'
    elif ID == 'UCMwGHR0BTZuLsmjY_NT5Pwg' : HoloName, live_tag, symbol  = '一伊那尓栖', '#TAKOTIME', '🐙'
    elif ID == 'UCoSrY_IQQVpmIRZ9Xf-y93g' : HoloName, live_tag, symbol  = 'がうる・ぐら', '#gawrgura', '🔱'
    elif ID == 'UCyl1z3jo3XHR1riLFKG5UAg' : HoloName, live_tag, symbol  = 'ワトソン・アメリア', '#amelive', '🔎'
    #ホロライブ ID
    elif ID == 'UCOyYb1c43VlX9rc_lT6NKQw' : HoloName, live_tag, symbol  = 'アユンダ・リス', '#Risu_Live', '🐿'
    elif ID == 'UCP0BspO_AMEe3aQqqpo89Dg' : HoloName, live_tag, symbol  = 'ムーナ・ホシノヴァ', '#MoonA_Live', '🔮'
    elif ID == 'UCAoy6rzhSf4ydcYjJw3WoVg' : HoloName, live_tag, symbol  =  'アイラニ・イオフィフティーン', '#ioLYFE', '🎨'
    elif ID == 'UCYz_5n-uDuChHtLo7My1HnQ' : HoloName, live_tag, symbol  =  'クレイジー・オリー', '#Kureiji_Ollie', '🧟‍♀️'
    elif ID == 'UC727SQYUvx5pDDGQpTICNWg' : HoloName, live_tag, symbol  =  'アーニャ・メルフィッサ', '#Anya_Melfissa', '🍂'
    elif ID == 'UChgTyjG-pdNvxxhdsXfHQ5Q' : HoloName, live_tag, symbol  =  'パヴォリア・レイネ', '#Pavolive', '🦚'
    # 運営
    elif ID == 'UCJFZiqLMntJufDCHc6bQixg' : HoloName, live_tag, symbol  = 'Hololive','#Hololive', '▶️'
    # 絵師
    elif ID == 'UCt30jJgChL8qeT9VPadidSw' : HoloName, live_tag, symbol  = 'しぐれうい', '#ういなま', '🌂'
    # のりプロ
    elif ID == 'UC8NZiqKx6fsDT3AVcMiVFyA' : HoloName, live_tag, symbol  = '犬山たまき', '#犬山たまき', '🐶'
    elif ID == 'UCC0i9nECi4Gz7TU63xZwodg' : HoloName, live_tag, symbol  = '白雪みしろ', '#白雪みしろ', '❄️'
    elif ID == 'UCJCzy0Fyrm0UhIrGQ7tHpjg' : HoloName, live_tag, symbol  = '愛宮みるく', '#愛宮みくる', '🍼'
    elif ID == 'UCle1cz6rcyH0a-xoMYwLlAg' : HoloName, live_tag, symbol  = '姫咲ゆずる', '姫咲ゆずる', '🐰'
    elif ID == 'UCLyTXfCZtl7dyhta9Jg3pZg' : HoloName, live_tag, symbol  = '鬼灯わらべ', '#鬼灯わらべ', '👹'
    elif ID == 'UCH11P1Hq4PXdznyw1Hhr3qw' : HoloName, live_tag, symbol  = '夢乃リリス', '#夢乃リリス', '🏩'
    elif ID == 'UCxrmkJf_X1Yhte_a4devFzA' : HoloName, live_tag, symbol  = '胡桃澤もも', '#胡桃澤もも', '🎀'
    elif ID == 'UCBAeKqEIugv69Q2GIgcH7oA' : HoloName, live_tag, symbol  = '逢魔きらら', '#逢魔きらら', '👿'
    elif ID == 'UCIRzELGzTVUOARi3Gwf1-yg' : HoloName, live_tag, symbol  = '看谷にぃあ', '#看谷にぃあ', '🌙❤️'
    return HoloName, live_tag, symbol 